# Generated by Django 2.2.1 on 2019-06-30 14:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='authority', verbose_name='official image')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authority',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumer',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateTimeField()),
                ('type', models.CharField(choices=[('suggestion', 'suggestion'), ('website problem bug', 'website problem bug')], default='suggestion', max_length=100)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Authority', verbose_name='Authority')),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('action_taken', models.TextField()),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Authority', verbose_name='Authority')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Officer', verbose_name='Officer')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Response',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('open', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Authority', verbose_name='Authority')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Category', verbose_name='Category')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Consumer', verbose_name='Consumer')),
            ],
            options={
                'verbose_name': 'complaint',
                'verbose_name_plural': 'complaint',
            },
        ),
    ]
