# Generated by Django 2.2.1 on 2019-07-03 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190703_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Complaint', verbose_name='Complaint'),
        ),
    ]
